# Generated by Django 4.1.2 on 2022-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_contact_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='profile_picture',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
