# Generated by Django 4.1.2 on 2022-12-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_register_table_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='register_table',
            name='profril_image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
