# Generated by Django 4.1.2 on 2022-12-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_remove_register_table_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_table',
            old_name='profril_image',
            new_name='profile_image',
        ),
    ]
