# Generated by Django 4.1.2 on 2022-12-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_rename_profril_image_register_table_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_table',
            name='profile_image',
        ),
    ]
