# Generated by Django 4.1.2 on 2023-01-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_remove_register_table_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
    ]
