# Generated by Django 4.1.2 on 2023-01-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_register_table_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
