# Generated by Django 4.1.2 on 2023-02-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_delete_register_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(upload_to='documents')),
            ],
        ),
    ]
